-- VRAM Governor — initial schema (architecture.md §32 Suggested Data Model)
--
-- Apply this migration and every later numbered migration for a production
-- controller. The in-memory store remains available only for development and
-- deterministic tests.
--
-- Conventions:
--   * IDs are text (ULID/UUID generated by the application), not serials.
--   * Enum-like fields are TEXT + CHECK constraints for portability.
--   * Large payloads (canonical session content, token blobs, KV snapshots,
--     job input/output, result manifests) are NOT stored here — only
--     `*_ref` pointers into object storage (architecture.md §8A.5, §41).

BEGIN;

-- ============================================================================
-- Nodes & accelerators (Phase 1 — implemented in-memory; this is the target
-- Postgres shape)
-- ============================================================================

CREATE TABLE nodes (
    id                   TEXT PRIMARY KEY,
    name                 TEXT NOT NULL,
    location_class       TEXT NOT NULL CHECK (location_class IN ('local', 'remote')),
    priority_tier        TEXT NOT NULL CHECK (priority_tier IN ('P0', 'P1', 'P2')),
    scheduling_state     TEXT NOT NULL CHECK (scheduling_state IN ('enabled', 'draining', 'disabled')),

    -- desired state (§14)
    desired_scheduling_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    desired_power        TEXT NOT NULL CHECK (desired_power IN ('on', 'off', 'unknown')) DEFAULT 'unknown',
    desired_pool         TEXT,
    auto_reconcile       BOOLEAN NOT NULL DEFAULT TRUE,
    power_control_mode   TEXT NOT NULL CHECK (power_control_mode IN ('auto', 'manual', 'off', 'dont_touch', 'external')),

    -- observed state (§14)
    observed_connectivity TEXT NOT NULL CHECK (observed_connectivity IN ('connected', 'suspect', 'lost', 'offline')) DEFAULT 'offline',
    observed_lifecycle    TEXT NOT NULL DEFAULT 'offline',
    observed_power        TEXT NOT NULL CHECK (observed_power IN ('on', 'off', 'unknown')) DEFAULT 'unknown',
    observed_ready        BOOLEAN NOT NULL DEFAULT FALSE,
    last_heartbeat        TIMESTAMPTZ,
    last_seen_at          TIMESTAMPTZ,
    agent_version         TEXT,

    registered_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE accelerators (
    id                    TEXT PRIMARY KEY,
    node_id               TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    vendor                TEXT NOT NULL,
    model                 TEXT NOT NULL,
    vram_total_mb         BIGINT NOT NULL,
    driver                TEXT,
    runtime_capabilities  JSONB, -- §6 capabilities object

    -- live telemetry, refreshed on every heartbeat/telemetry message (§34A)
    vram_used_mb          BIGINT NOT NULL DEFAULT 0,
    vram_free_mb          BIGINT NOT NULL DEFAULT 0,
    utilization_pct       DOUBLE PRECISION NOT NULL DEFAULT 0,
    temperature_c         DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_accelerators_node_id ON accelerators(node_id);

-- ============================================================================
-- Models & serving profiles (Phase 2+)
-- ============================================================================

CREATE TABLE model_artifacts (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    revision      TEXT NOT NULL,
    quantization  TEXT,
    format        TEXT,
    tokenizer     TEXT,
    source        TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (name, revision, quantization, format)
);

CREATE TABLE serving_profiles (
    id                TEXT PRIMARY KEY,
    model_artifact_id TEXT NOT NULL REFERENCES model_artifacts(id) ON DELETE CASCADE,
    runtime           TEXT NOT NULL,       -- e.g. vllm, llamacpp
    context_limit     INTEGER NOT NULL,
    kv_reservation_mb BIGINT,
    max_sequences     INTEGER,
    runtime_args      JSONB,
    expected_vram_mb  BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE engine_instances (
    id                    TEXT PRIMARY KEY,
    node_id               TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    accelerator_id        TEXT REFERENCES accelerators(id) ON DELETE SET NULL,
    profile_id            TEXT NOT NULL REFERENCES serving_profiles(id),
    managed_by_controller BOOLEAN NOT NULL DEFAULT TRUE,
    pid                   INTEGER,
    state                 TEXT NOT NULL, -- e.g. active_full, sleep_ram, evicted, draining... (§7)
    started_at            TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_engine_instances_node_id ON engine_instances(node_id);

CREATE TABLE worker_pools (
    id                    TEXT PRIMARY KEY,
    model_artifact_id     TEXT NOT NULL REFERENCES model_artifacts(id),
    policy                TEXT,
    desired_min_shards    INTEGER NOT NULL DEFAULT 0,
    desired_max_shards    INTEGER NOT NULL DEFAULT 0,
    logical_worker_limit  INTEGER,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Sessions (lead continuity — §8A, §32). Only small structured fields live
-- here; canonical/token/KV *content* lives in object storage by reference.
-- ============================================================================

CREATE TABLE sessions (
    id                  TEXT PRIMARY KEY,
    lead_model_alias    TEXT NOT NULL,
    bindings            JSONB NOT NULL, -- model_artifact/quantization/tokenizer/template/system_prompt (§8A.1)
    canonical_state_ref TEXT NOT NULL,  -- authoritative turns + decode params (object store)
    token_state_ref     TEXT,           -- tokenized cache (§8A.2), valid iff version matches
    continuation_state  JSONB,          -- awaiting_batch record, or NULL (§8A.1)
    version             BIGINT NOT NULL DEFAULT 0, -- monotonic; committed before any sleep/evict (§8A.5)
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Jobs & work items (§12, §32) — at-least-once execution with dedupe.
-- ============================================================================

CREATE TABLE jobs (
    id          TEXT PRIMARY KEY,
    operation   TEXT NOT NULL,
    pool        TEXT,
    status      TEXT NOT NULL CHECK (status IN ('queued', 'running', 'paused', 'completed', 'completed_with_errors', 'cancelled', 'failed')),
    input_ref   TEXT,
    output_ref  TEXT,
    priority    TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE work_items (
    job_id            TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    item_id           TEXT NOT NULL,
    operation_version TEXT NOT NULL,
    state             TEXT NOT NULL CHECK (state IN ('queued', 'leased', 'running', 'success', 'failed', 'lease_expired')),
    lease_owner       TEXT,       -- node_id currently holding the lease
    lease_expiry      TIMESTAMPTZ,
    attempt           INTEGER NOT NULL DEFAULT 0,
    result_ref        TEXT,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- identity per §12: job_id + item_id + operation_version
    PRIMARY KEY (job_id, item_id, operation_version)
);

CREATE INDEX idx_work_items_state ON work_items(state);
CREATE INDEX idx_work_items_lease_owner ON work_items(lease_owner);

-- ============================================================================
-- Transition plans (§31, §32) — explainable scheduler decisions.
-- ============================================================================

CREATE TABLE transition_plans (
    id                         TEXT PRIMARY KEY,
    reason                     TEXT NOT NULL,
    steps                      JSONB NOT NULL,      -- ordered list of planned actions
    rollback                   JSONB,                -- ordered list of rollback actions
    estimated_duration_seconds DOUBLE PRECISION,
    estimated_memory_change_mb BIGINT,
    status                     TEXT NOT NULL CHECK (status IN ('planned', 'executing', 'completed', 'failed', 'rolled_back')),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Events (§28, §32) — human-readable lifecycle audit trail, distinct from
-- raw runtime logs.
-- ============================================================================

CREATE TABLE events (
    id          BIGSERIAL PRIMARY KEY,
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
    node_id     TEXT REFERENCES nodes(id) ON DELETE SET NULL,
    job_id      TEXT REFERENCES jobs(id) ON DELETE SET NULL,
    session_id  TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    type        TEXT NOT NULL,
    severity    TEXT NOT NULL CHECK (severity IN ('debug', 'info', 'warn', 'error')),
    payload     JSONB
);

CREATE INDEX idx_events_timestamp ON events("timestamp");
CREATE INDEX idx_events_node_id ON events(node_id);
CREATE INDEX idx_events_job_id ON events(job_id);

COMMIT;
