import React, { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { api, Login, Shell, Status, usePoll, Workload } from "./common";
import "./studio.css";

type Explanation = {transformation_approvals:any[];transition_plans:any[];events:{id:string;timestamp:string;type:string}[]};

function WorkloadRow({row,refresh}:{row:Workload;refresh:()=>void}) {
  const [priority,setPriority]=useState(row.runtime_priority ?? row.request.priority);
  const [busy,setBusy]=useState(false), [message,setMessage]=useState("");
  const [explanation,setExplanation]=useState<Explanation|null>(null);
  async function mutate(path:string,body?:unknown) { setBusy(true);setMessage("");try{await api(path,{method:"POST",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});refresh()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)} }
  async function explain(){setBusy(true);setMessage("");try{setExplanation(await api<Explanation>(`/api/v1/workloads/${row.request.id}/explain`))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  const terminal=["succeeded","failed","cancelled","rejected"].includes(row.status);
  return <article className="workload-card">
    <div className="row"><div className="adapter">{row.request.adapter.slice(0,2).toUpperCase()}</div><div><strong>{row.request.workload_type||row.request.adapter}</strong><code>{row.request.id}</code><span>{row.decision?.target_id||row.decision?.blocker||"awaiting placement"}</span></div><Status value={row.status}/></div>
    <div className="workload-meta"><span>QoS {row.request.qos||"normal"}</span><span>Priority {row.runtime_priority ?? row.request.priority}</span><span>Progress {Math.round((row.progress||0)*100)}%</span><span>Confidence {Math.round((row.decision?.confidence||0)*100)}%</span>{row.preemption_count?<span>Preempted {row.preemption_count}×</span>:null}</div>
    {row.status==="running"&&<div className="workload-progress"><i style={{width:`${Math.max(2,Math.round((row.progress||0)*100))}%`}}/><span>{row.progress_stage?.replaceAll("_"," ")||"executing"}{row.progress_node?` · node ${row.progress_node}`:""}{row.progress_total?` · ${row.progress_current||0}/${row.progress_total}`:""}</span></div>}
    {row.decision?.estimated_start&&<small>Estimated start {new Date(row.decision.estimated_start).toLocaleString()}</small>}
    {row.decision?.alternatives?.length?<details><summary>Placement explanation</summary><ul>{row.decision.alternatives.map(reason=><li key={reason}>{reason}</li>)}</ul></details>:null}
    {row.plan?.transformations?.length?<div className="transform-preview"><strong>Transformation preview</strong><code>{row.plan.plan_hash}</code><span>{row.plan.transformations.join(" · ")}</span>{row.status==="pending_approval"&&<button disabled={busy} onClick={()=>mutate(`/api/v1/workloads/${row.request.id}/approve`,{plan_hash:row.plan!.plan_hash,mode:"ask"})}>Approve exact plan</button>}</div>:null}
    {!terminal&&<div className="inline-controls"><input type="number" min="0" max="100" value={priority} onChange={e=>setPriority(Number(e.target.value))}/><button className="quiet" disabled={busy} onClick={()=>mutate(`/api/v1/workloads/${row.request.id}/priority`,{priority})}>Reprioritize</button><button className="quiet danger" disabled={busy} onClick={()=>mutate(`/api/v1/workloads/${row.request.id}/cancel`)}>Cancel</button></div>}
    <button className="quiet explain-button" disabled={busy} onClick={explain}>{explanation?"Refresh decision trace":"Open decision trace"}</button>
    {explanation&&<details open className="decision-trace"><summary>Durable decision trace</summary><div className="trace-grid"><span><small>Plan</small><code>{row.plan?.plan_hash||"not placed"}</code></span><span><small>Approvals</small><strong>{explanation.transformation_approvals?.length||0}</strong></span><span><small>Transitions</small><strong>{explanation.transition_plans?.length||0}</strong></span><span><small>Events</small><strong>{explanation.events?.length||0}</strong></span></div><ol>{explanation.events?.slice().reverse().map(event=><li key={event.id}><time>{new Date(event.timestamp).toLocaleTimeString()}</time><strong>{event.type}</strong></li>)}</ol></details>}
    {(Boolean(row.output_refs?.length)||row.inline_output!==undefined)&&<details><summary>Outputs</summary>{row.output_refs?.map(id=><a key={id} href={`/view?filename=${encodeURIComponent(id)}&type=output`} target="_blank" rel="noreferrer"><code>{id}</code></a>)}{row.inline_output!==undefined&&<pre>{JSON.stringify(row.inline_output,null,2)}</pre>}</details>}
    {row.error&&<div className="error">{row.error}</div>}{message&&<div className="error">{message}</div>}
  </article>;
}

type ModelCatalog = {data:{id:string}[]};
type PlacementPreview = {recommended_target?:string;requirements:{model?:string;context_tokens?:number};candidates:{target_id:string;eligible:boolean;blocker?:string;context_limit?:number;slots:number;available_slots:number;resident:boolean;residency_action?:string;estimated_start?:string;confidence:number}[]};

function Studio(){
  const [ready,setReady]=useState(false);
  const {data:rows,error,refresh}=usePoll<Workload[]>(ready?"/api/v1/workloads":null,[],1500);
  const {data:models}=usePoll<ModelCatalog>(ready?"/v1/models":null,{data:[]},10000);
  const [adapter,setAdapter]=useState("llamacpp"), [model,setModel]=useState("local-model"), [prompt,setPrompt]=useState("Give a one-sentence health check for this GPU fleet."), [payload,setPayload]=useState('{"prompt":"Describe this task."}');
  const [priority,setPriority]=useState(20), [qos,setQos]=useState("normal"), [disruption,setDisruption]=useState("locked"), [contextTokens,setContextTokens]=useState(256), [maxOutput,setMaxOutput]=useState(128);
  const [frames,setFrames]=useState(0), [width,setWidth]=useState(0), [height,setHeight]=useState(0), [steps,setSteps]=useState(0), [deadline,setDeadline]=useState(""), [placementPolicy,setPlacementPolicy]=useState("best_fit"), [placementKey,setPlacementKey]=useState("");
  const [transforms,setTransforms]=useState(""), [transformParams,setTransformParams]=useState('{"reduce_steps":{"max_steps":20},"reduce_resolution":{"max_width":1024,"max_height":1024}}'), [submitError,setSubmitError]=useState(""), [preview,setPreview]=useState<PlacementPreview|null>(null), [previewBusy,setPreviewBusy]=useState(false);
  useEffect(()=>{if(models.data.length&&(model==="local-model"||!models.data.some(row=>row.id===model)))setModel(models.data[0].id)},[models,model]);
  useEffect(()=>{if(adapter==="openrouter"&&disruption==="cancelable")setDisruption("locked")},[adapter,disruption]);
  if(!ready)return <Login onReady={()=>setReady(true)}/>;
  function requestBody(){const transformations=transforms.split(",").map(v=>v.trim()).filter(Boolean);const requestPayload=adapter==="llamacpp"?{model,messages:[{role:"user",content:prompt}],max_completion_tokens:maxOutput||128,stream:false}:JSON.parse(payload);return {adapter,workload_type:adapter==="comfy"?"comfy.workflow":"llm.chat",payload:requestPayload,priority,qos,deadline:deadline?new Date(deadline).toISOString():undefined,queue_policy:"wait",disruption,egress:adapter==="openrouter"?"cloud_allowed":"local_only",recoverable:adapter==="comfy"||adapter==="openrouter",placement_policy:placementPolicy,placement_key:placementKey||undefined,bounds:{context_tokens:contextTokens,max_output:maxOutput,frames,width,height,steps},transformation_policy:"ask",transformations,transformation_parameters:JSON.parse(transformParams)}}
  async function showPreview(){setPreviewBusy(true);setSubmitError("");try{setPreview(await api<PlacementPreview>("/api/v1/workloads/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(requestBody())}))}catch(e){setSubmitError((e as Error).message)}finally{setPreviewBusy(false)}}
  async function submit(e:FormEvent){e.preventDefault();setSubmitError("");try{await api("/api/v1/workloads",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(requestBody())});setPreview(null);refresh()}catch(e){setSubmitError((e as Error).message)}}
  const active=rows.filter(r=>r.status==="running").length, waiting=rows.filter(r=>["queued","waiting","pending_approval"].includes(r.status)).length, done=rows.filter(r=>r.status==="succeeded").length;
  return <Shell title="Agent activity" section="studio">
    <section className="metrics"><article><small>Running now</small><strong>{active}</strong><span>active accelerator leases</span></article><article><small>Waiting / review</small><strong>{waiting}</strong><span>queued or awaiting approval</span></article><article><small>Finished</small><strong>{done}</strong><span>durable successful runs</span></article></section>
    <section className="agent-first"><div><div className="eyebrow">Agent-first gateway</div><h2>Your agents submit; this page explains what happened.</h2><p>OpenAI clients, asynchronous agents, and Comfy workflows all share the same physical GPU inventory and policy engine.</p></div><div className="endpoint-list"><code>POST /v1/chat/completions</code><code>POST /api/v1/workloads</code><code>POST /prompt</code><code>POST /api/v1/workloads/preview</code></div></section>
    <section className="panel queue activity-ledger"><div className="panel-head"><div><div className="eyebrow">Live activity</div><h2>Requests, placement & outputs</h2></div><button className="quiet" onClick={refresh}>Refresh</button></div>{error&&<div className="error banner">{error}</div>}<div className="rows">{rows.length===0?<div className="empty">No requests yet. Agents can start sending work whenever they are ready.</div>:rows.slice().reverse().map(row=><WorkloadRow row={row} refresh={refresh} key={row.request.id}/>)}</div></section>
    <details className="panel manual-launch"><summary><div><div className="eyebrow">Optional diagnostic tool</div><h2>Preview or run a task manually</h2><p>The preview calls the real scheduler but creates no workload, lease, model load, or budget reservation.</p></div><span>Open runner</span></summary><form onSubmit={submit}>
      <div className="form-grid"><label>Runtime<select value={adapter} onChange={e=>setAdapter(e.target.value)}><option value="llamacpp">Local LLM</option><option value="comfy">ComfyUI</option><option value="openrouter">Cloud fallback</option><option value="mock">Mock verification</option></select></label><label>Service level<select value={qos} onChange={e=>setQos(e.target.value)}><option value="interactive">Interactive</option><option value="normal">Normal</option><option value="background">Background</option></select></label></div>
      {adapter==="llamacpp"?<><label>Model{models.data.length?<select value={model} onChange={e=>setModel(e.target.value)}>{models.data.map(row=><option value={row.id} key={row.id}>{row.id}</option>)}</select>:<input value={model} onChange={e=>setModel(e.target.value)} placeholder="model ID"/>}</label><label>Prompt<textarea rows={5} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label></>:<label>Request JSON<textarea rows={10} value={payload} onChange={e=>setPayload(e.target.value)} spellCheck={false}/></label>}
      <details className="advanced-controls"><summary>Scheduling controls</summary><div className="form-grid"><label>Disruption policy<select value={disruption} onChange={e=>setDisruption(e.target.value)}><option value="locked">Do not interrupt</option><option value="slowdown_allowed">Sharing allowed</option>{adapter!=="openrouter"&&<option value="cancelable">May cancel (no resume)</option>}</select><small>Yield and checkpoint are hidden until a connected runtime proves those operations.</small></label><label>Priority <output>{priority}</output><input type="range" min="0" max="100" value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label><label>Deadline<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label>Placement<select value={placementPolicy} onChange={e=>setPlacementPolicy(e.target.value)}><option value="best_fit">Best available fit</option><option value="sticky">Keep this client pinned</option></select></label><label>Client or session key<input value={placementKey} onChange={e=>setPlacementKey(e.target.value)} placeholder="required for sticky"/></label><label>Context budget<input type="number" min="0" value={contextTokens} onChange={e=>setContextTokens(Number(e.target.value))}/></label><label>Maximum output<input type="number" min="0" value={maxOutput} onChange={e=>setMaxOutput(Number(e.target.value))}/></label><label>Frames / width / height / steps<div className="bound-grid"><input type="number" min="0" value={frames} onChange={e=>setFrames(Number(e.target.value))}/><input type="number" min="0" value={width} onChange={e=>setWidth(Number(e.target.value))}/><input type="number" min="0" value={height} onChange={e=>setHeight(Number(e.target.value))}/><input type="number" min="0" value={steps} onChange={e=>setSteps(Number(e.target.value))}/></div></label><label>Allowed transforms<input value={transforms} placeholder="reduce_steps, reduce_resolution" onChange={e=>setTransforms(e.target.value)}/></label><label>Transform rules JSON<textarea rows={4} value={transformParams} onChange={e=>setTransformParams(e.target.value)} spellCheck={false}/></label></div></details>
      <div className="runner-actions"><button type="button" className="quiet" disabled={previewBusy} onClick={showPreview}>{previewBusy?"Evaluating…":"Preview placement"}</button><button>Run task</button></div>{submitError&&<div className="error">{submitError}</div>}
      {preview&&<section className="placement-preview"><div><div className="eyebrow">Zero-side-effect scheduler preview</div><h3>{preview.recommended_target?`Recommended: ${preview.recommended_target}`:"No eligible target"}</h3><p>{preview.requirements.model||adapter} · {preview.requirements.context_tokens||0} context tokens</p></div><div className="candidate-grid">{preview.candidates.map(candidate=><article className={candidate.eligible?"eligible":"blocked"} key={candidate.target_id}><div><strong>{candidate.target_id}</strong><Status value={candidate.eligible?"eligible":"blocked"}/></div><code>{candidate.context_limit||"unknown"} ctx · {candidate.available_slots}/{candidate.slots} slots · {candidate.resident?"resident":candidate.residency_action||"cold"}</code><p>{candidate.blocker||`ETA ${candidate.estimated_start?new Date(candidate.estimated_start).toLocaleTimeString():"now"} · ${Math.round(candidate.confidence*100)}% confidence`}</p></article>)}</div></section>}
    </form></details>
  </Shell>
}
createRoot(document.getElementById("root")!).render(<Studio/>);
